Repository Team-momo-front/momo-front, pull requests merged in 2024-12, with the labels that each got.

#7 feat: LoginPage
  src/App.tsx
  src/assets/svg/kakaoIcon.svg
  src/components/Header/Header.tsx
  src/components/Input.tsx
  src/components/Login/LoginForm.tsx
  src/index.css
  src/pages/LoginPage.tsx
  src/router/Router.tsx
Labels: enhancement

#10 [Feat] 게시물 검색창 UI 구현
  package.json
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/Select.tsx
  yarn.lock
Labels: enhancement, UI

#14 [Feat] 회원가입 페이지 UI 구현 #13
  src/components/Header/Header.tsx
  src/components/Input.tsx
  src/components/Join/JoinField.tsx.tsx
  src/components/Join/JoinForm.tsx
  src/pages/JoinPage.tsx
  src/router/Router.tsx
  tailwind.config.js
Labels: enhancement, UI

#16 [Feat] 회원가입 유효성 검사 구현
  src/components/Input.tsx
  src/components/Join/JoinForm.tsx
  src/components/Join/validation.ts
  src/components/types/types.ts
Labels: enhancement

#19 [Feat] 회원가입 유효성 검사
  src/components/Input.tsx
  src/components/Join/JoinField.tsx.tsx
  src/components/Join/JoinForm.tsx
  src/components/Join/validation.ts
  src/components/types/JoinErrorMessages.ts
  src/utils/formatPhoneNumber.ts
Labels: enhancement

#22 [Enhancement]daisyUI 적용하여 디자인 리팩토링 및 인증 코드 입력 기능 추가
  src/components/Header/Header.tsx
  src/components/Input.tsx
  src/components/Join/JoinField.tsx.tsx
  src/components/Join/JoinForm.tsx
  src/components/Join/validation.ts
  src/components/Login/LoginForm.tsx
  src/index.css
  src/types/JoinErrorMessages.ts
  tailwind.config.js
Labels: enhancement

#26 ✨ Feat: 게시물 생성 페이지 UI 구현
  public/image/upload_image.webp
  src/components/FormField.tsx
  src/hooks/useCreatePostForm.ts
  src/pages/CreatePostPage.tsx
  src/router/Router.tsx
Labels: UI, feature
