Repository Team-momo-front/momo-front, pull requests merged in 2025-01, with the labels that each got.

#35 ✨ [Feat] 회원 탈퇴 페이지 구현
  src/assets/svg/kakaoIcon.svg
  src/components/Join/CreateProfile.tsx
  src/components/Login/LoginForm.tsx
  src/components/MyPage/AccountDeletion.tsx
  src/components/MyPage/MyInfo.tsx
  src/components/MyPage/Nav.tsx
  src/components/MyPage/UserInfo.tsx
  src/router/Router.tsx
  src/states/recoilState.ts
Labels: enhancement, UI

#33 ✨ [Feat] 비밀번호 변경 컴포넌트 구현
  src/assets/svg/kakaoIcon.svg
  src/components/Join/CreateProfile.tsx
  src/components/Join/validation.ts
  src/components/Login/LoginForm.tsx
  src/components/MyPage/AccountDeletion.tsx
  src/components/MyPage/ChangePassword.tsx
  src/components/MyPage/MyInfo.tsx
  src/components/MyPage/Nav.tsx
  src/components/MyPage/UserInfo.tsx
  src/router/Router.tsx
  src/types/User.ts
Labels: UI

#31 ✨[Feat] 마이페이지 내 정보 페이지 구현
  public/image/default_profile_image.webp
  src/App.tsx
  src/assets/svg/kakaoIcon.svg
  src/components/Join/CreateProfile.tsx
  src/components/Join/JoinField.tsx
  src/components/Join/JoinForm.tsx
  src/components/Join/validation.ts
  src/components/Login/LoginForm.tsx
  src/components/MyPage/AccountDeletion.tsx
  src/components/MyPage/ChangePassword.tsx
  src/components/MyPage/InfoFormField.tsx
  src/components/MyPage/MyInfo.tsx
  src/components/MyPage/Nav.tsx
  src/components/MyPage/UserInfo.tsx
  src/components/ProfileImageUpload.tsx
  src/hooks/useMBTIValidation.ts
  src/index.css
  src/mocks/users.ts
  src/pages/MyPage.tsx
  src/router/Router.tsx
  src/states/recoilState.ts
  src/types/User.ts
  src/utils/convertGenderToLabel.ts
  tailwind.config.js
Labels: enhancement, UI

#29 🚀[Feat] 프로필 생성 페이지 기능 구현
  public/image/default_profile_image.webp
  public/image/upload_profile_image.webp
  src/App.tsx
  src/assets/svg/kakaoIcon.svg
  src/components/Header/Header.tsx
  src/components/Input.tsx
  src/components/Join/CreateProfile.tsx
  src/components/Join/JoinField.tsx
  src/components/Join/JoinField.tsx.tsx
  src/components/Join/JoinForm.tsx
  src/components/Join/validation.ts
  src/components/Login/LoginForm.tsx
  src/components/MyPage/AccountDeletion.tsx
  src/components/MyPage/ChangePassword.tsx
  src/components/MyPage/InfoFormField.tsx
  src/components/MyPage/MyInfo.tsx
  src/components/MyPage/Nav.tsx
  src/components/MyPage/UserInfo.tsx
  src/components/ProfileImageUpload.tsx
  src/hooks/useMBTIValidation.ts
  src/index.css
  src/mocks/users.ts
  src/pages/CreateProfilePage.tsx
  src/pages/MyPage.tsx
  src/router/Router.tsx
  src/states/recoilState.ts
  src/types/User.ts
  src/utils/convertGenderToLabel.ts
  tailwind.config.js
Labels: enhancement, UI

#37 [Feat] 게시물 생성 페이지 장소검색 기능 구현
  .gitignore
  index.html
  package.json
  public/image/upload_image.webp
  src/components/modals/KakaoMapModal.tsx
  src/hooks/useCreatePostForm.ts
  src/pages/CreatePostPage.tsx
  src/types/Post.ts
  vite.config.ts
  yarn.lock
Labels: feature

#47 🎉 [Feat] 참가한 모임 컴포넌트 구현 및 상태 관리 리팩토링
  src/components/MyPage/HostedMeetings.tsx
  src/components/MyPage/MyMeetings.tsx
  src/components/MyPage/ParticipatedMeetings.tsx
  src/components/PostCard.tsx
  src/components/PostCardBtn.tsx
  src/mocks/posts.ts
  src/states/recoilState.ts
  src/types/Post.ts
  src/utils/getStatusAndColorByRole.ts
Labels: enhancement, UI

#39 ✨ Feat: 게시글 생성 페이지 추가기능 구현
  src/components/FormField.tsx
  src/components/modals/KakaoMapModal.tsx
  src/pages/CreatePostPage.tsx
  src/utils/getLocalDateTime.ts
Labels: feature

#41 ✨ Feat: 내 주변 검색 기능 구현
  src/components/SearchBar/SearchBar.tsx
  src/mocks/posts.ts
  src/pages/ListPage.tsx
  src/types/Post.ts
  src/utils/calculateDistance.ts
Labels: feature

#50 💄 Feat: 게시글 기본 썸네일 추가
  public/image/thumbnail_default.webp
  public/image/thumbnail_example.webp
  src/components/PostCard.tsx
Labels: UI, feature

#45 ✨ [Feat] 로그인 유저 헤더 UI
  src/components/Header/Header.tsx
Labels: enhancement, UI

#43 ✨ [Feat] 내 모임 관리 페이지 주최한 모임 UI
  src/components/Header/Header.tsx
  src/components/Join/CreateProfile.tsx
  src/components/Join/JoinForm.tsx
  src/components/MyPage/ChangePassword.tsx
  src/components/MyPage/HostedMeetings.tsx
  src/components/MyPage/MyInfo.tsx
  src/components/MyPage/MyMeetings.tsx
  src/components/MyPage/Nav.tsx
  src/components/MyPage/ParticipatedMeetings.tsx
  src/components/PostCard.tsx
  src/components/PostCardBtn.tsx
  src/mocks/posts.ts
  src/router/Router.tsx
  src/states/recoilState.ts
  src/types/Errors.ts
  src/types/Post.ts
  src/utils/getStatusAndColorByRole.ts
Labels: enhancement, UI

#54 [Feat] 상세페이지 구현
  src/components/Categories.tsx
  src/components/PostCard.tsx
  src/mocks/posts.ts
  src/pages/DetailPage.tsx
  src/pages/ListPage.tsx
  src/router/Router.tsx
  src/types/Post.ts
Labels: UI, ROUTER, feature

#55 ✨ [Feat] 신청자 보기 페이지 UI
  src/components/MyPage/HostedMeetings.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/PostCard.tsx
  src/components/PostCardBtn.tsx
  src/mocks/posts.ts
  src/mocks/users.ts
  src/pages/ViewParticipantPage.tsx
  src/router/Router.tsx
  src/types/User.ts
  src/utils/getStatusAndColorByRole.ts
Labels: UI

#59 ✨ Feat: 상세페이지 버튼 상태별 구현
  src/pages/DetailPage.tsx
Labels: UI, feature

#57 ✨ feat(profile): 유저 프로필 보기 페이지 생성
  index.html
  public/favicon.svg
  src/assets/svg/logo.svg
  src/components/MyPage/InfoFormField.tsx
  src/components/MyPage/MyInfo.tsx
  src/components/MyPage/MyProfile.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/MyPage/UserInfo.tsx
  src/components/PostCardBtn.tsx
  src/components/UserProfileBtn.tsx
  src/pages/UserProfilePage.tsx
  src/router/Router.tsx
  src/types/User.ts
  src/utils/calculateAge.ts
  tailwind.config.js
Labels: UI

#64 [Feat] 알림 구현
  src/components/Header/Header.tsx
  src/mocks/notifications.ts
  src/types/Notification.ts
Labels: UI, feature

#65 ✨ Refactor: Layout 컴포넌트 구현 및 적용
  src/components/Chat/ChatList.tsx
  src/components/Chat/ChatModal.tsx
  src/components/Chat/ChatParticipantList.tsx
  src/components/Layout/Layout.tsx
  src/components/UserProfileBtn.tsx
  src/pages/CreateProfilePage.tsx
  src/pages/JoinPage.tsx
  src/pages/ListPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/ResetPasswordPage.tsx
  src/pages/UserProfilePage.tsx
  src/pages/ViewParticipantPage.tsx
  src/router/Router.tsx
Labels: UI

#69 🛠 [Refactor] btn-primary 컬러 변경
  tailwind.config.js
Labels: refactor

#71 [Refactor] Layout 사용하기
  src/pages/CreatePostPage.tsx
  src/pages/CreateProfilePage.tsx
  src/pages/DetailPage.tsx
  src/pages/JoinPage.tsx
  src/pages/ListPage.tsx
  src/pages/LoginPage.tsx
  src/pages/ResetPasswordPage.tsx
  src/pages/ViewParticipantPage.tsx
  src/router/Router.tsx
Labels: refactor

#73 ✨ Feat: 채팅모달 닫기 버튼
  public/chat.svg
  src/components/Chat/ChatFloatingBtn.tsx
  src/components/Chat/ChatList.tsx
Labels: enhancement, UI, refactor

#75 🏷️ Fix: 게시물 생성 request 데이터 타입 수정
  src/hooks/useCreatePostForm.ts
  src/pages/CreatePostPage.tsx
  src/types/Post.ts
Labels: invalid

#87 🐛 Fix: 타입오류 수정
  src/components/SearchBar/SearchBar.tsx
  src/pages/ListPage.tsx
  src/types/Post.ts
Labels: bug

#81 ✨ Feat: 게시물 생성 api 호출 훅
  src/api/axiosInstance.ts
  src/api/meeting.ts
  src/hooks/useCreateMeeting.ts
  src/router/Router.tsx
Labels: feature

#83 ✨ Feat: 게시글 생성하기
  src/components/modals/KakaoMapModal.tsx
  src/hooks/useCreatePostForm.ts
  src/pages/CreatePostPage.tsx
Labels: enhancement

#85 🐛 Fix: Header - map사용 시 key설정
  src/components/Header/Header.tsx
Labels: invalid

#90 ✨ Feat: axios interceptor 세팅 및 apiClient 구현
  eslint.config.js
  src/api/apiClient.ts
  src/api/axiosInstance.ts
Labels: enhancement

#94 ✨ [Feat] 카카오 로그인 구현
  src/components/Join/JoinForm.tsx
  src/components/Join/VerifyEmailCode.tsx
  src/components/Login/KakaoLogin.tsx
  src/components/Login/LoginForm.tsx
  src/router/Router.tsx
  src/states/recoilState.ts
  vite.config.ts
Labels: feature

#101 ✨ Feat: 모집 취소하기
  src/hooks/useDeleteMeeting.ts
  src/pages/ViewParticipantPage.tsx
Labels: feature

#102 ✨ [Feat] 로그아웃 구현
  src/components/Header/Header.tsx
  src/components/Join/VerifyEmailCode.tsx
  src/components/Login/KakaoLogin.tsx
  src/components/Login/LoginForm.tsx
  src/states/recoilState.ts
  vite.config.ts
Labels: feature

#105 ✨ [Feat] 프로필 조회 호출시 인터셉터 처리 추가
  src/api/axiosInstance.ts
  src/components/Header/Header.tsx
  src/components/Join/CreateProfile.tsx
  src/components/MyPage/InfoForm.tsx
  src/components/MyPage/MyProfile.tsx
  src/components/MyPage/Nav.tsx
  src/components/MyPage/ProfileRedirect.tsx
  src/hooks/useFetchUserProfile.ts
  src/router/Router.tsx
  src/states/recoilState.ts
  src/types/User.ts
  src/utils/convertGenderToLabel.ts
Labels: feature

#110 ♻️ Refactor: 메인페이지 리팩토링
  src/hooks/useDebounce.ts
  src/pages/ListPage.tsx
Labels: enhancement, refactor

#112 🐛 Fix: 게시물 조회 API 상태관리
  src/hooks/useSearchMeetings.ts
  src/pages/ListPage.tsx
Labels: bug, enhancement

#114 ✨ [Feat] 회원 탈퇴
  package.json
  src/components/MyPage/AccountDeletion.tsx
  yarn.lock
Labels: feature

#120 [Refactor] 상세페이지 리팩토링
  src/api/meeting.ts
  src/hooks/useCreatePostForm.ts
  src/hooks/useEditMeeting.ts
  src/hooks/useGetmyMeetings.ts
  src/mocks/meetings.ts
  src/pages/ApplyMeetingPage.tsx
  src/pages/DetailPage.tsx
  src/pages/PostEditPage.tsx
  src/types/Meeting.ts
  src/types/Post.ts
Labels: refactor

#122 ✨ [Feat] 비밀번호 재설정 기능 구현
  src/components/Join/RedirectResetPassword.tsx
  src/components/Join/ResetPassword.tsx
  src/router/Router.tsx
Labels: feature

#118 🐛 [Fix] 로그아웃 api 주소 수정
  src/components/Header/Header.tsx
  src/components/Join/RedirectResetPassword.tsx
  src/components/Join/ResetPassword.tsx
  src/components/Login/KakaoLogin.tsx
  src/components/Login/LoginForm.tsx
  src/router/Router.tsx
Labels: bug

#116 ♻️ [Refactor] 프로필 조회 API 호출 실패 시 재요청하는 로직 수정
  src/components/Header/Header.tsx
  src/components/Join/RedirectResetPassword.tsx
  src/components/Join/ResetPassword.tsx
  src/components/Login/KakaoLogin.tsx
  src/components/Login/LoginForm.tsx
  src/components/MyPage/MyProfile.tsx
  src/hooks/useFetchUserProfile.ts
  src/router/Router.tsx
Labels: refactor

#128 ♻️ Refactor: 상세페이지에 레이아웃 사용
  src/pages/ApplyMeetingPage.tsx
  src/pages/PostEditPage.tsx
Labels: refactor

#126 ✨ Feat: 상세페이지 레이아웃 컴포넌트 구현
  src/components/DetailPageLayout.tsx
  src/components/FormField.tsx
  src/pages/ApplyMeetingPage.tsx
  src/pages/PostEditPage.tsx
Labels: enhancement

#129 ✏️ Fix: 오기 수정
  src/hooks/useCreatePostForm.ts
Labels: bug

#131 💄 Fix: 게시글 생성 페이지 레이아웃 수정
  src/pages/CreatePostPage.tsx
Labels: invalid

#136 ♻️ [Refactor] 이메일 인증 완료 후 UI/UX 수정
  src/components/Join/CreateProfile.tsx
  src/components/Join/VerifyEmailCode.tsx
Labels: refactor

#134 ♻️ [Refactor] 프로필 페이지 리팩토링
  public/image/default_profile_image.webp
  public/image/default_profile_image_test.webp
  src/components/Join/CreateProfile.tsx
  src/components/Join/VerifyEmailCode.tsx
  src/components/MyPage/AccountDeletion.tsx
  src/components/MyPage/MyProfile.tsx
Labels: refactor

#132 ✨ [Feat] 비밀번호 변경 api 호출
  public/image/default_profile_image.webp
  public/image/default_profile_image_test.webp
  src/components/Join/CreateProfile.tsx
  src/components/Join/VerifyEmailCode.tsx
  src/components/MyPage/AccountDeletion.tsx
  src/components/MyPage/ChangePassword.tsx
  src/components/MyPage/MyProfile.tsx
Labels: feature

#146 🐛 [Fix] 프로필 생성 리다이렉트 주소 절대경로로 수정
  src/components/Join/CreateProfile.tsx
Labels: bug

#149 ✨ Feat: 로딩스피너 컴포넌트
  src/components/LoadingSpinner.tsx
  src/components/MyPage/AccountDeletion.tsx
  src/components/MyPage/MyProfile.tsx
  src/pages/ListPage.tsx
Labels: UI

#144 ♻️ [Refactor] 로그인 로딩 상태 및 에러 처리 개선
  src/components/Login/KakaoLogin.tsx
  src/components/Login/LoginForm.tsx
Labels: refactor

#142 ♻️ [Refactor] 로그아웃 로딩 상태 및 에러 처리 개선
  src/components/Header/Header.tsx
  src/components/Join/VerifyEmailCode.tsx
  src/components/Login/KakaoLogin.tsx
  src/components/Login/LoginForm.tsx
Labels: refactor

#138 ♻️ [Refactor] 회원가입 AxiosInstance 사용 및 로딩 상태 및 에러 처리
  src/components/Header/Header.tsx
  src/components/Join/JoinForm.tsx
  src/components/Join/VerifyEmailCode.tsx
  src/components/Login/KakaoLogin.tsx
  src/components/Login/LoginForm.tsx
  src/components/MyPage/ChangePassword.tsx
  src/components/MyPage/Nav.tsx
  src/router/Router.tsx
Labels: refactor

#150 ♻️ [Refactor] 비밀번호 재설정 컴포넌트 상태 관리 개선
  src/components/Join/RedirectResetPassword.tsx
  src/components/Join/ResetPassword.tsx
Labels: refactor

#161 ✨ Feat: 신청자 목록 불러오기
  src/components/MyPage/ParticipantList.tsx
  src/hooks/useGetParticipants.ts
  src/types/User.ts
Labels: feature

#159 ✨ Feat: 모집완료 기능 구현
  src/hooks/useCloseMeeting.ts
  src/pages/ViewParticipantPage.tsx
Labels: feature

#180 ♻️ [Refactor] Thumbnail을 파일데이터로 보내도록 모집글 생성시 formdata 전달하도록 수정
  src/api/meeting.ts
  src/hooks/useCreatePostForm.ts
  src/pages/CreatePostPage.tsx
  src/types/Meeting.ts
Labels: refactor

#178 ♻️ [Refactor] 프로필 이미지 업로드 개선
  public/image/default_profile_image.png
  src/api/meeting.ts
  src/components/Header/Header.tsx
  src/components/Join/CreateProfile.tsx
  src/components/MyPage/MyProfile.tsx
  src/components/ProfileImageUpload.tsx
  src/hooks/useCreatePostForm.ts
  src/pages/CreatePostPage.tsx
  src/types/Meeting.ts
Labels: refactor

#174 ✨ [Feat] 모집 완료되었을 때 채팅방 생성 호출
  public/image/default_profile_image.png
  src/api/meeting.ts
  src/components/Chat/ChatList.tsx
  src/components/Header/Header.tsx
  src/components/Join/CreateProfile.tsx
  src/components/MyPage/MyProfile.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/ProfileImageUpload.tsx
  src/hooks/useCloseMeeting.ts
  src/hooks/useCreateChatroom.ts
  src/hooks/useCreatePostForm.ts
  src/hooks/useGetParticipants.ts
  src/pages/CreatePostPage.tsx
  src/pages/ViewParticipantPage.tsx
  src/router/Router.tsx
  src/types/Chat.ts
  src/types/Meeting.ts
  src/types/User.ts
  tailwind.config.js
Labels: feature

#172 🐛 [FIX] 모집글 생성 API 호출시 카테고리 값 서버 요청값에 맞게 변환
  public/image/default_profile_image.png
  src/api/meeting.ts
  src/components/Chat/ChatList.tsx
  src/components/Header/Header.tsx
  src/components/Join/CreateProfile.tsx
  src/components/MyPage/MyProfile.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/ProfileImageUpload.tsx
  src/hooks/useCloseMeeting.ts
  src/hooks/useCreateChatroom.ts
  src/hooks/useCreatePostForm.ts
  src/hooks/useGetParticipants.ts
  src/pages/CreatePostPage.tsx
  src/pages/ViewParticipantPage.tsx
  src/router/Router.tsx
  src/types/Chat.ts
  src/types/Meeting.ts
  src/types/User.ts
  tailwind.config.js
Labels: bug

#168 ✨ [Feat] Chat 목록 조회 API 연동
  package.json
  src/api/chatrooms.ts
  src/components/Chat/ChatList.tsx
  src/components/Chat/ChatModal.tsx
  src/hooks/useSearchChatRooms.ts
  src/types/Chat.ts
  yarn.lock
Labels: feature

#170 ♻️ [Refactor] 401 오류 발생시 액세스 토큰 갱신 & 카카오 로그인 중복 호출 오류 수정
  public/image/default_profile_image.png
  src/api/axiosInstance.ts
  src/api/meeting.ts
  src/api/refreshAccessToken.ts
  src/components/Chat/ChatList.tsx
  src/components/Header/Header.tsx
  src/components/Join/CreateProfile.tsx
  src/components/Login/KakaoLogin.tsx
  src/components/MyPage/MyProfile.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/ProfileImageUpload.tsx
  src/hooks/useCloseMeeting.ts
  src/hooks/useCreateChatroom.ts
  src/hooks/useCreatePostForm.ts
  src/hooks/useGetParticipants.ts
  src/pages/CreatePostPage.tsx
  src/pages/ViewParticipantPage.tsx
  src/router/Router.tsx
  src/types/Chat.ts
  src/types/Meeting.ts
  src/types/User.ts
  tailwind.config.js
Labels: refactor

#166 ♻️ [Refactor] 프로필 페이지 403 오류 처리 및 카카오 유저 프로필 데이터 개선
  package.json
  public/image/default_profile_image.png
  public/image/default_profile_image.webp
  public/image/default_profile_image_test.webp
  src/api/axiosInstance.ts
  src/api/chatrooms.ts
  src/api/meeting.ts
  src/api/refreshAccessToken.ts
  src/components/Chat/ChatList.tsx
  src/components/Chat/ChatModal.tsx
  src/components/Header/Header.tsx
  src/components/Join/CreateProfile.tsx
  src/components/Login/KakaoLogin.tsx
  src/components/Login/LoginForm.tsx
  src/components/MyPage/AccountDeletion.tsx
  src/components/MyPage/MyProfile.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/ProfileImageUpload.tsx
  src/hooks/useCloseMeeting.ts
  src/hooks/useCreateChatroom.ts
  src/hooks/useCreatePostForm.ts
  src/hooks/useEditProfile.ts
  src/hooks/useFetchUserProfile.ts
  src/hooks/useGetParticipants.ts
  src/hooks/useSearchChatRooms.ts
  src/pages/CreatePostPage.tsx
  src/pages/ViewParticipantPage.tsx
  src/router/Router.tsx
  src/types/Chat.ts
  src/types/Meeting.ts
  src/types/User.ts
  tailwind.config.js
  yarn.lock
Labels: refactor

#164 ♻️ [Refactor] 탈퇴하기 컴포넌트 상태 개선
  package.json
  public/image/default_profile_image.png
  public/image/default_profile_image.webp
  public/image/default_profile_image_test.webp
  src/api/axiosInstance.ts
  src/api/chatrooms.ts
  src/api/meeting.ts
  src/api/refreshAccessToken.ts
  src/components/Chat/ChatList.tsx
  src/components/Chat/ChatModal.tsx
  src/components/Header/Header.tsx
  src/components/Join/CreateProfile.tsx
  src/components/Login/KakaoLogin.tsx
  src/components/Login/LoginForm.tsx
  src/components/MyPage/AccountDeletion.tsx
  src/components/MyPage/MyProfile.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/ProfileImageUpload.tsx
  src/hooks/useCloseMeeting.ts
  src/hooks/useCreateChatroom.ts
  src/hooks/useCreatePostForm.ts
  src/hooks/useEditProfile.ts
  src/hooks/useFetchUserProfile.ts
  src/hooks/useGetParticipants.ts
  src/hooks/useSearchChatRooms.ts
  src/pages/CreatePostPage.tsx
  src/pages/ViewParticipantPage.tsx
  src/router/Router.tsx
  src/types/Chat.ts
  src/types/Meeting.ts
  src/types/User.ts
  tailwind.config.js
  yarn.lock
Labels: UI, refactor

#162 ✨ [Feat] 프로필 수정 기능 구현
  package.json
  public/image/default_profile_image.png
  public/image/default_profile_image.webp
  public/image/default_profile_image_test.webp
  src/api/axiosInstance.ts
  src/api/chatrooms.ts
  src/api/meeting.ts
  src/api/refreshAccessToken.ts
  src/components/Chat/ChatList.tsx
  src/components/Chat/ChatModal.tsx
  src/components/Header/Header.tsx
  src/components/Join/CreateProfile.tsx
  src/components/Login/KakaoLogin.tsx
  src/components/Login/LoginForm.tsx
  src/components/MyPage/AccountDeletion.tsx
  src/components/MyPage/InfoForm.tsx
  src/components/MyPage/MyProfile.tsx
  src/components/MyPage/Nav.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/ProfileImageUpload.tsx
  src/hooks/useCloseMeeting.ts
  src/hooks/useCreateChatroom.ts
  src/hooks/useCreatePostForm.ts
  src/hooks/useEditProfile.ts
  src/hooks/useFetchUserProfile.ts
  src/hooks/useGetParticipants.ts
  src/hooks/useSearchChatRooms.ts
  src/pages/CreatePostPage.tsx
  src/pages/ViewParticipantPage.tsx
  src/router/Router.tsx
  src/states/recoilState.ts
  src/types/Chat.ts
  src/types/Meeting.ts
  src/types/User.ts
  tailwind.config.js
  yarn.lock
Labels: feature

#154 ✨[Feat] Protected Route 설정
  package.json
  public/image/default_profile_image.png
  public/image/default_profile_image.webp
  public/image/default_profile_image_test.webp
  src/api/axiosInstance.ts
  src/api/chatrooms.ts
  src/api/meeting.ts
  src/api/refreshAccessToken.ts
  src/components/Chat/ChatList.tsx
  src/components/Chat/ChatModal.tsx
  src/components/Header/Header.tsx
  src/components/Join/CreateProfile.tsx
  src/components/Layout/Layout.tsx
  src/components/Login/KakaoLogin.tsx
  src/components/Login/LoginForm.tsx
  src/components/MyPage/AccountDeletion.tsx
  src/components/MyPage/InfoForm.tsx
  src/components/MyPage/MyProfile.tsx
  src/components/MyPage/Nav.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/ProfileImageUpload.tsx
  src/components/ProtectedRoute/ProtectedRoute.tsx
  src/hooks/useCloseMeeting.ts
  src/hooks/useCreateChatroom.ts
  src/hooks/useCreatePostForm.ts
  src/hooks/useEditProfile.ts
  src/hooks/useFetchUserProfile.ts
  src/hooks/useGetParticipants.ts
  src/hooks/useSearchChatRooms.ts
  src/pages/CreatePostPage.tsx
  src/pages/ViewParticipantPage.tsx
  src/router/Router.tsx
  src/states/recoilState.ts
  src/types/Chat.ts
  src/types/Meeting.ts
  src/types/User.ts
  tailwind.config.js
  yarn.lock
Labels: feature

#152 ♻️ [Refactor] 프로필 조회 페이지 상태 관리 개선
  package.json
  public/image/default_profile_image.png
  public/image/default_profile_image.webp
  public/image/default_profile_image_test.webp
  src/api/axiosInstance.ts
  src/api/chatrooms.ts
  src/api/meeting.ts
  src/api/refreshAccessToken.ts
  src/components/Chat/ChatList.tsx
  src/components/Chat/ChatModal.tsx
  src/components/Header/Header.tsx
  src/components/Join/CreateProfile.tsx
  src/components/Layout/Layout.tsx
  src/components/Login/KakaoLogin.tsx
  src/components/Login/LoginForm.tsx
  src/components/MyPage/AccountDeletion.tsx
  src/components/MyPage/InfoForm.tsx
  src/components/MyPage/MyProfile.tsx
  src/components/MyPage/Nav.tsx
  src/components/ProfileImageUpload.tsx
  src/components/ProtectedRoute/ProtectedRoute.tsx
  src/hooks/useCreateChatroom.ts
  src/hooks/useCreatePostForm.ts
  src/hooks/useEditProfile.ts
  src/hooks/useFetchUserProfile.ts
  src/hooks/useSearchChatRooms.ts
  src/pages/CreatePostPage.tsx
  src/pages/ViewParticipantPage.tsx
  src/router/Router.tsx
  src/states/recoilState.ts
  src/types/Chat.ts
  src/types/Meeting.ts
  src/types/User.ts
  tailwind.config.js
  yarn.lock
Labels: refactor

#196 ✨ [Feat] 모집글 보기 & 신청자 보기 버튼
  src/components/Login/LoginForm.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/PostCard.tsx
  src/components/PostCardBtn.tsx
  src/pages/ViewParticipantPage.tsx
  src/types/Meeting.ts
  src/types/Post.ts
Labels: feature

#192 ✨ [Feat] 모임 신청 기능 구현
  src/api/meeting.ts
  src/api/paricipations.ts
  src/components/Login/LoginForm.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/MyPage/ParticipatedMeetings.tsx
  src/components/PostCard.tsx
  src/components/PostCardBtn.tsx
  src/hooks/useGetMyParticipatedMeetings.ts
  src/hooks/useParticipateMeeting.ts
  src/pages/ApplyMeetingPage.tsx
  src/pages/PostEditPage.tsx
  src/pages/ViewParticipantPage.tsx
  src/types/Meeting.ts
  src/types/Post.ts
  src/utils/getStatusAndColorByRole.ts
Labels: feature

#190 ✨ [Feat] 주최한 목록 조회 페이지 개선
  src/api/meeting.ts
  src/api/paricipations.ts
  src/components/Login/LoginForm.tsx
  src/components/MyPage/HostedMeetings.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/MyPage/ParticipatedMeetings.tsx
  src/components/PostCard.tsx
  src/components/PostCardBtn.tsx
  src/hooks/useGetMyParticipatedMeetings.ts
  src/hooks/useGetmyMeetings.ts
  src/hooks/useParticipateMeeting.ts
  src/pages/ApplyMeetingPage.tsx
  src/pages/PostEditPage.tsx
  src/pages/ViewParticipantPage.tsx
  src/types/Meeting.ts
  src/types/Post.ts
  src/utils/convertMeetingsToPosts.ts
  src/utils/getStatusAndColorByRole.ts
Labels: feature

#186 ✨ [Feat] 메인페이지 리팩토링
  public/image/default_post_thumbnail.png
  public/image/thumbnail_default.webp
  src/api/meeting.ts
  src/api/paricipations.ts
  src/components/DetailPageLayout.tsx
  src/components/Login/LoginForm.tsx
  src/components/MyPage/HostedMeetings.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/MyPage/ParticipatedMeetings.tsx
  src/components/PostCard.tsx
  src/components/PostCardBtn.tsx
  src/hooks/useGetMyParticipatedMeetings.ts
  src/hooks/useGetmyMeetings.ts
  src/hooks/useParticipateMeeting.ts
  src/hooks/useSearchMeetings.ts
  src/pages/ApplyMeetingPage.tsx
  src/pages/DetailPage.tsx
  src/pages/ListPage.tsx
  src/pages/PostEditPage.tsx
  src/pages/ViewParticipantPage.tsx
  src/types/Meeting.ts
  src/types/Post.ts
  src/utils/convertMeetingsToPosts.ts
  src/utils/getStatusAndColorByRole.ts
Labels: refactor

#199 🐛 fix: type 오류 수정
  src/hooks/useFetchUserProfile.ts
Labels: bug

#203 ♻️ [Refactor] 채팅 버튼 렌더링 수정
  src/components/Chat/ChatFloatingBtn.tsx
  src/components/Chat/ChatModal.tsx
  src/components/Chat/ChatParticipantList.tsx
  src/components/Chat/ChatRoom.tsx
  src/components/Layout/Layout.tsx
  src/hooks/useSearchChatRooms.ts
  src/states/recoilState.ts
Labels: refactor

#205 🐛 fix : 프로필 수정 요청값 updateData로 수정
  src/components/MyPage/MyProfile.tsx
Labels: bug
