Repository Team-momo-front/momo-front, pull requests merged in 2025-02, with the labels that each got.

#211 ✨ [Feat] 신청한 모집글 상세 페이지에서 버튼 렌더링 구현(신청자 입장)
  src/api/paricipations.ts
  src/components/DetailPageLayout.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/MyPage/ParticipatedMeetings.tsx
  src/components/UserProfileBtn.tsx
  src/hooks/useDeleteParticipation.ts
  src/hooks/useGetMyParticipatedMeetings.ts
  src/hooks/useGetUserProfile.ts
  src/pages/ApplyMeetingPage.tsx
  src/pages/UserProfilePage.tsx
  src/router/Router.tsx
  src/types/User.ts
Labels: feature, refactor

#209 ♻️ [Refactor] 신청자 보기 리팩토링
  src/api/meeting.ts
  src/api/paricipations.ts
  src/components/DetailPageLayout.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/MyPage/ParticipatedMeetings.tsx
  src/components/UserProfileBtn.tsx
  src/hooks/useDeleteParticipation.ts
  src/hooks/useGetMyParticipatedMeetings.ts
  src/hooks/useGetParticipants.ts
  src/hooks/useGetUserProfile.ts
  src/pages/ApplyMeetingPage.tsx
  src/pages/UserProfilePage.tsx
  src/pages/ViewParticipantPage.tsx
  src/router/Router.tsx
  src/types/User.ts
Labels: refactor

#207 ♻️ [Refactor] 모집글 수정
  src/api/meeting.ts
  src/api/paricipations.ts
  src/components/DetailPageLayout.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/MyPage/ParticipatedMeetings.tsx
  src/components/UserProfileBtn.tsx
  src/hooks/useDeleteParticipation.ts
  src/hooks/useEditMeeting.ts
  src/hooks/useGetMyParticipatedMeetings.ts
  src/hooks/useGetParticipants.ts
  src/hooks/useGetUserProfile.ts
  src/pages/ApplyMeetingPage.tsx
  src/pages/CreatePostPage.tsx
  src/pages/DetailPage.tsx
  src/pages/PostEditPage.tsx
  src/pages/UserProfilePage.tsx
  src/pages/ViewParticipantPage.tsx
  src/router/Router.tsx
  src/types/User.ts
  src/utils/categoryValueToKey.ts
Labels: refactor

#215 ♻️ [Refactor] 신청 취소 API participationId 값 수정
  src/hooks/useGetMyParticipatedMeetings.ts
  src/hooks/useParticipateMeeting.ts
  src/pages/ApplyMeetingPage.tsx
  src/types/Meeting.ts
Labels: refactor

#217 ✨ [Feat] 알림구현
  package-lock.json
  package.json
  src/components/Header/Header.tsx
  src/hooks/useNotifications.ts
  yarn.lock
Labels: feature

#229 ✨ [Feat] 모임 삭제 & 모임 상태 변경(모집 완료) 구현
  src/components/PostCardBtn.tsx
  src/hooks/useCloseMeeting.ts
  src/hooks/useDeleteMeeting.ts
  src/router/Router.tsx
  src/types/Meeting.ts
Labels: feature

#239 ♻️ [Refactor] 참여 승인 / 거절 API 호출 성공 이벤트 처리 개선
  src/components/MyPage/ParticipantList.tsx
  src/components/UserProfileBtn.tsx
  src/hooks/useApproveParticipation.ts
  src/hooks/useGetParticipants.ts
  src/hooks/useRejectParticipation.ts
  src/router/Router.tsx
Labels: refactor

#237 ♻️ [Refactor] 모임 취소 API 호출 성공시 페이지 재렌더링 리팩토링
  src/components/MyPage/ParticipantList.tsx
  src/components/UserProfileBtn.tsx
  src/hooks/useApproveParticipation.ts
  src/hooks/useDeleteMeeting.ts
  src/hooks/useGetParticipants.ts
  src/hooks/useRejectParticipation.ts
  src/router/Router.tsx
Labels: refactor

#235 ♻️ [Refactor] 마이페이지 내 모임 빈 배열 렌더링 처리 추가
  src/components/MyPage/HostedMeetings.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/MyPage/ParticipatedMeetings.tsx
  src/components/UserProfileBtn.tsx
  src/hooks/useApproveParticipation.ts
  src/hooks/useDeleteMeeting.ts
  src/hooks/useGetParticipants.ts
  src/hooks/useRejectParticipation.ts
  src/router/Router.tsx
Labels: UI, refactor

#234 ✨ [Feat] 채팅 뒤로가기 구현
  src/api/chatrooms.ts
  src/components/Chat/ChatModal.tsx
  src/components/MyPage/HostedMeetings.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/MyPage/ParticipatedMeetings.tsx
  src/components/UserProfileBtn.tsx
  src/hooks/useApproveParticipation.ts
  src/hooks/useDeleteMeeting.ts
  src/hooks/useGetOutChatRoom.ts
  src/hooks/useGetParticipants.ts
  src/hooks/useRejectParticipation.ts
  src/router/Router.tsx
Labels: feature

#231 ♻️ [Refactor] 채팅 기본이미지 설정 및 카카오 유저 닉네임 기본값 설정
  src/api/chatrooms.ts
  src/components/Chat/ChatList.tsx
  src/components/Chat/ChatModal.tsx
  src/components/Chat/ChatRoom.tsx
  src/components/MyPage/HostedMeetings.tsx
  src/components/MyPage/ParticipantList.tsx
  src/components/MyPage/ParticipatedMeetings.tsx
  src/components/UserProfileBtn.tsx
  src/hooks/useApproveParticipation.ts
  src/hooks/useDeleteMeeting.ts
  src/hooks/useGetOutChatRoom.ts
  src/hooks/useGetParticipants.ts
  src/hooks/useRejectParticipation.ts
  src/router/Router.tsx
Labels: refactor

#242 🐛 Fix: 카테고리 필수입력 처리
  src/hooks/useCreatePostForm.ts
  src/pages/CreatePostPage.tsx
Labels: bug

#244 🐛 Fix: 비로그인시 유저정보 API 호출 비활성화
  src/components/Header/Header.tsx
  src/hooks/useFetchUserProfile.ts
Labels: bug

#249 ♻️ Refactor: useEditProfile 리팩토링
  src/components/MyPage/MyProfile.tsx
  src/hooks/useEditProfile.ts
Labels: refactor

#258 🐛 [fix] 모집 취소 API 호출 성공시 리다이렉트 수정
  src/hooks/useDeleteMeeting.ts
Labels: bug

#257 ♻️ [Feat] 채팅 참여자 강퇴
  src/components/UserProfileBtn.tsx
  src/hooks/useWithdrawChatParticipant.ts
Labels: refactor

#252 ✨ [Feat] 채팅 참여자 조회
  src/components/Chat/ChatParticipantList.tsx
  src/components/UserProfileBtn.tsx
  src/hooks/useGetChatParticipants.ts
  src/hooks/useWithdrawChatParticipant.ts
  src/pages/UserProfilePage.tsx
  src/types/Chat.ts
Labels: feature

#263 ✨ [Feat] 신청한 모임 목록 모집글 카드 삭제 버튼 구현
  src/components/PostCardBtn.tsx
  src/hooks/useDeleteMeeting.ts
  src/hooks/useDeleteParticipation.ts
  src/pages/ApplyMeetingPage.tsx
Labels: feature

#261 ♻️ [Refactor] 모임 상태 변경 API -> 모집 완료 API로 변경
  src/api/meeting.ts
  src/components/PostCardBtn.tsx
  src/hooks/useCloseMeeting.ts
  src/hooks/useDeleteMeeting.ts
  src/hooks/useDeleteParticipation.ts
  src/pages/ApplyMeetingPage.tsx
  src/types/Meeting.ts
Labels: refactor

#267 🐛 Fix: 알림창 가려짐 수정
  src/components/Header/Header.tsx
Labels: invalid, UI

#268 ✨ [Feat] 주최자 입장 채팅방 삭제
  src/components/Chat/ChatAlert.tsx
  src/components/Chat/ChatParticipantList.tsx
  src/components/PostCardBtn.tsx
  src/hooks/useDeleteMeeting.ts
  src/pages/ViewParticipantPage.tsx
Labels: feature

#272 ♻️ [Refactor] 프로필 조회 403에러 처리를 통해 프로필 생성 페이지로 유도
  src/api/axiosInstance.ts
  src/components/Header/Header.tsx
  src/components/Join/CreateProfile.tsx
  src/components/MyPage/AccountDeletion.tsx
  src/components/MyPage/MyProfile.tsx
  src/components/MyPage/ProfileRedirect.tsx
  src/components/MyPage/ProfileRedirectModal.tsx
  src/hooks/useMyProfile.ts
Labels: refactor

#270 ✨ [Feat] 채팅방 퇴장 = 모임 나가기 기능 (신청자)
  src/api/axiosInstance.ts
  src/components/Chat/ChatAlert.tsx
  src/components/Header/Header.tsx
  src/components/Join/CreateProfile.tsx
  src/components/MyPage/AccountDeletion.tsx
  src/components/MyPage/MyProfile.tsx
  src/components/MyPage/ProfileRedirect.tsx
  src/components/MyPage/ProfileRedirectModal.tsx
  src/hooks/useLeaveChatRoom.ts
  src/hooks/useMyProfile.ts
Labels: feature

#278 ♻️ [Refactor] 채팅 모달에서 채팅 삭제 후 모임 리스트 업데이트 개선
  src/components/MyPage/HostedMeetings.tsx
  src/hooks/useDeleteMeeting.ts
  src/hooks/useGetmyMeetings.ts
Labels: refactor

#276 ♻️ [Refactor] users API 공용 컴포넌트로 리팩토링
  src/api/apiClient.ts
  src/api/uesrs.ts
  src/components/Header/Header.tsx
  src/components/Join/JoinForm.tsx
  src/components/Join/RedirectResetPassword.tsx
  src/components/Join/ResetPassword.tsx
  src/components/Join/VerifyEmailCode.tsx
  src/components/Login/LoginForm.tsx
  src/components/MyPage/AccountDeletion.tsx
  src/components/MyPage/HostedMeetings.tsx
  src/hooks/useDeleteMeeting.ts
  src/hooks/useEditProfile.ts
  src/hooks/useGetUserProfile.ts
  src/hooks/useGetmyMeetings.ts
  src/hooks/useMyProfile.ts
  src/types/User.ts
Labels: refactor

#274 ♻️ [Refactor] 카카오 유저 닉네임 기본값 수정
  src/api/apiClient.ts
  src/api/getMyProfile.ts
  src/api/uesrs.ts
  src/components/Chat/ChatParticipantList.tsx
  src/components/Chat/ChatRoom.tsx
  src/components/Header/Header.tsx
  src/components/Join/JoinForm.tsx
  src/components/Join/RedirectResetPassword.tsx
  src/components/Join/ResetPassword.tsx
  src/components/Join/VerifyEmailCode.tsx
  src/components/Login/LoginForm.tsx
  src/components/MyPage/AccountDeletion.tsx
  src/components/MyPage/HostedMeetings.tsx
  src/components/MyPage/ParticipantList.tsx
  src/hooks/useDeleteMeeting.ts
  src/hooks/useEditProfile.ts
  src/hooks/useGetUserProfile.ts
  src/hooks/useGetmyMeetings.ts
  src/hooks/useMyProfile.ts
  src/pages/UserProfilePage.tsx
  src/types/User.ts
Labels: refactor

#280 🐛 Fix: 함수 호출하기
  src/components/Header/Header.tsx
Labels: bug
